### ISSUE TITLE
Game crashes when you drop a bounty on the ground

### ISSUE THREAD

**Issue by Nano-the-Hero** [kyber-6/avalon-modpack#1]
### Describe the bug

If you drop a bounty on the ground, the game will instantly crash with a render error. It will keep crashing on bootup if the bounty is still on the ground, which may result in a crashloop until the item despawns or is picked up. Judging from the log it is a mod conflict between the bountyfull and loot beams.

### Reproduction steps

Simply throw any bounty on the ground.

### Logs & crash-reports

[crash-2023-12-17_14.03.15-client.txt](https://github.com/kyber-6/avalon-modpack/files/13706539/crash-2023-12-17_14.03.15-client.txt)

### Mod pack version

2.1.0 (The latest)

**Comment by KevzCz** [comment]
Alright fixed, it will be in the next update
