### ISSUE TITLE
Webballs bypass claims

### ISSUE THREAD

**Issue by Nano-the-Hero** [kyber-6/avalon-modpack#2]
### Describe the bug

You can throw a webball in somebodies claim and it may spawn a cobweb bypassing the claim restrictions.
Sidenote: Can somebody please remove the cobweb which I accidentally created right on the server spawn point, it is a bit of an inconvinience and some ppl even complained.

### Reproduction steps

Just start throwing webbballs in somebodies claim. (Well obviously dont)

### Mod pack version

2.1.0 (The latest)

**Comment by KevzCz** [comment]
Will ask the server mods for this
