### ISSUE TITLE
Problem with modded server

### ISSUE THREAD

**Issue by Thelemonek** [kyber-6/avalon-modpack#3]
### Describe the bug

when i am downloading modpack for server it doesn't work good with normal modpack it says "mod missing"

### Reproduction steps

e

### Screenshots

e

### Logs & crash-reports

e

### Mod pack version

2.5.0

**Comment by KevzCz** [comment]
Are there no logs?

**Comment by Thelemonek** [comment]
logs from server console ?

**Comment by Thelemonek** [comment]
okay i just removed some mods and everything works
THANKS
